// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: analytics.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsightsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActivityId     string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimeStream     []int32                `protobuf:"varint,3,rep,packed,name=time_stream,json=timeStream,proto3" json:"time_stream,omitempty"`
	VelocityStream []float32              `protobuf:"fixed32,4,rep,packed,name=velocity_stream,json=velocityStream,proto3" json:"velocity_stream,omitempty"`
	HrStream       []int32                `protobuf:"varint,5,rep,packed,name=hr_stream,json=hrStream,proto3" json:"hr_stream,omitempty"`
	AltitudeStream []float32              `protobuf:"fixed32,6,rep,packed,name=altitude_stream,json=altitudeStream,proto3" json:"altitude_stream,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InsightsRequest) Reset() {
	*x = InsightsRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightsRequest) ProtoMessage() {}

func (x *InsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightsRequest.ProtoReflect.Descriptor instead.
func (*InsightsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *InsightsRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *InsightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsightsRequest) GetTimeStream() []int32 {
	if x != nil {
		return x.TimeStream
	}
	return nil
}

func (x *InsightsRequest) GetVelocityStream() []float32 {
	if x != nil {
		return x.VelocityStream
	}
	return nil
}

func (x *InsightsRequest) GetHrStream() []int32 {
	if x != nil {
		return x.HrStream
	}
	return nil
}

func (x *InsightsRequest) GetAltitudeStream() []float32 {
	if x != nil {
		return x.AltitudeStream
	}
	return nil
}

type PacePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds   int64                  `protobuf:"varint,1,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	RealPace      float64                `protobuf:"fixed64,2,opt,name=real_pace,json=realPace,proto3" json:"real_pace,omitempty"`
	PredictedPace float64                `protobuf:"fixed64,3,opt,name=predicted_pace,json=predictedPace,proto3" json:"predicted_pace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacePoint) Reset() {
	*x = PacePoint{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacePoint) ProtoMessage() {}

func (x *PacePoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacePoint.ProtoReflect.Descriptor instead.
func (*PacePoint) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *PacePoint) GetTimeSeconds() int64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *PacePoint) GetRealPace() float64 {
	if x != nil {
		return x.RealPace
	}
	return 0
}

func (x *PacePoint) GetPredictedPace() float64 {
	if x != nil {
		return x.PredictedPace
	}
	return 0
}

// A single finding produced by one analyzer in the pipeline. The `type`
// discriminator (e.g. "AEROBIC_DECOUPLING", "PACING_PENALTY", "TERRAIN")
// lets the BFF render each insight without the proto knowing the concrete
// model. Extra fields go in `metadata` as stringified scalars.
type ActivityInsight struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Summary          string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	SeverityScore    float64                `protobuf:"fixed64,3,opt,name=severity_score,json=severityScore,proto3" json:"severity_score,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PointTimeSeconds int32                  `protobuf:"varint,5,opt,name=point_time_seconds,json=pointTimeSeconds,proto3" json:"point_time_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivityInsight) Reset() {
	*x = ActivityInsight{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInsight) ProtoMessage() {}

func (x *ActivityInsight) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInsight.ProtoReflect.Descriptor instead.
func (*ActivityInsight) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityInsight) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActivityInsight) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ActivityInsight) GetSeverityScore() float64 {
	if x != nil {
		return x.SeverityScore
	}
	return 0
}

func (x *ActivityInsight) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ActivityInsight) GetPointTimeSeconds() int32 {
	if x != nil {
		return x.PointTimeSeconds
	}
	return 0
}

type InsightsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActivityId          string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	CombinedAiNarrative string                 `protobuf:"bytes,2,opt,name=combined_ai_narrative,json=combinedAiNarrative,proto3" json:"combined_ai_narrative,omitempty"`
	DiscreteInsights    []*ActivityInsight     `protobuf:"bytes,3,rep,name=discrete_insights,json=discreteInsights,proto3" json:"discrete_insights,omitempty"`
	PacingChartData     []*PacePoint           `protobuf:"bytes,4,rep,name=pacing_chart_data,json=pacingChartData,proto3" json:"pacing_chart_data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InsightsResponse) Reset() {
	*x = InsightsResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightsResponse) ProtoMessage() {}

func (x *InsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightsResponse.ProtoReflect.Descriptor instead.
func (*InsightsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *InsightsResponse) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *InsightsResponse) GetCombinedAiNarrative() string {
	if x != nil {
		return x.CombinedAiNarrative
	}
	return ""
}

func (x *InsightsResponse) GetDiscreteInsights() []*ActivityInsight {
	if x != nil {
		return x.DiscreteInsights
	}
	return nil
}

func (x *InsightsResponse) GetPacingChartData() []*PacePoint {
	if x != nil {
		return x.PacingChartData
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\"\xdb\x01\n" +
	"\x0fInsightsRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtime_stream\x18\x03 \x03(\x05R\n" +
	"timeStream\x12'\n" +
	"\x0fvelocity_stream\x18\x04 \x03(\x02R\x0evelocityStream\x12\x1b\n" +
	"\thr_stream\x18\x05 \x03(\x05R\bhrStream\x12'\n" +
	"\x0faltitude_stream\x18\x06 \x03(\x02R\x0ealtitudeStream\"r\n" +
	"\tPacePoint\x12!\n" +
	"\ftime_seconds\x18\x01 \x01(\x03R\vtimeSeconds\x12\x1b\n" +
	"\treal_pace\x18\x02 \x01(\x01R\brealPace\x12%\n" +
	"\x0epredicted_pace\x18\x03 \x01(\x01R\rpredictedPace\"\x97\x02\n" +
	"\x0fActivityInsight\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12%\n" +
	"\x0eseverity_score\x18\x03 \x01(\x01R\rseverityScore\x12D\n" +
	"\bmetadata\x18\x04 \x03(\v2(.analytics.ActivityInsight.MetadataEntryR\bmetadata\x12,\n" +
	"\x12point_time_seconds\x18\x05 \x01(\x05R\x10pointTimeSeconds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x01\n" +
	"\x10InsightsResponse\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x122\n" +
	"\x15combined_ai_narrative\x18\x02 \x01(\tR\x13combinedAiNarrative\x12G\n" +
	"\x11discrete_insights\x18\x03 \x03(\v2\x1a.analytics.ActivityInsightR\x10discreteInsights\x12@\n" +
	"\x11pacing_chart_data\x18\x04 \x03(\v2\x14.analytics.PacePointR\x0fpacingChartData2b\n" +
	"\x10AnalyticsService\x12N\n" +
	"\x13GetActivityInsights\x12\x1a.analytics.InsightsRequest\x1a\x1b.analytics.InsightsResponseB7Z5endurance-hub/analytics/internal/infra/pb;analyticspbb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analytics_proto_goTypes = []any{
	(*InsightsRequest)(nil),  // 0: analytics.InsightsRequest
	(*PacePoint)(nil),        // 1: analytics.PacePoint
	(*ActivityInsight)(nil),  // 2: analytics.ActivityInsight
	(*InsightsResponse)(nil), // 3: analytics.InsightsResponse
	nil,                      // 4: analytics.ActivityInsight.MetadataEntry
}
var file_analytics_proto_depIdxs = []int32{
	4, // 0: analytics.ActivityInsight.metadata:type_name -> analytics.ActivityInsight.MetadataEntry
	2, // 1: analytics.InsightsResponse.discrete_insights:type_name -> analytics.ActivityInsight
	1, // 2: analytics.InsightsResponse.pacing_chart_data:type_name -> analytics.PacePoint
	0, // 3: analytics.AnalyticsService.GetActivityInsights:input_type -> analytics.InsightsRequest
	3, // 4: analytics.AnalyticsService.GetActivityInsights:output_type -> analytics.InsightsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
